[package]
name = "goodmorning-services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.4"
chrono = "0.4"
serde = "1.0"
fastrand = "1.9"
hex = "0.4"
sha2 = "0.10"
async-trait = "0.1"
lettre = { version = "0.10", features = ["tokio1", "tokio1-native-tls"] }
dyn-clone = "1.0"
typetag = "0.2"
actix-web = "4.3"
tokio = "1.26"
dotenv = "0.15"
env_logger = "0.10"

[dev-dependencies]
