[package]
name = "goodmorning-services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3"
async-trait = "0.1"
chrono = "0.4"
dotenv = "0.15"
dyn-clone = "1.0"
env_logger = "0.10"
fastrand = "1.9"
hex = "0.4"
lettre = { version = "0.10", features = ["tokio1", "tokio1-native-tls"] }
mongodb = "2.4"
serde = "1.0"
sha2 = "0.10"
tokio = "1.26"
typetag = "0.2"
actix-multipart = "0.6"
futures-util = "0.3"
async-recursion = "1.0"

[dev-dependencies]
